name: whisper-api
version: 0.1.1
apiVersion: v1
appVersion: "1.0"
description: A Helm chart for whisper-api
sources:
- https://github.com/cbsiamlg/splice/whisper
maintainers:
- name: Justin Nguyen 
  email: JustinNguyen@paramount.com